services:
  postgres:
    image: postgres:13
    container_name: articles-postgres
    environment:
      POSTGRES_DB: articles_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
      image: redis:7-alpine
      container_name: articles-redis
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      restart: unless-stopped
      command: redis-server --appendonly yes


volumes:
  postgres_data:
  redis_data: